openapi: 3.0.0
info:
  title: API de Productos y Carrito de Compras
  version: 1.0.0
  description: Documentación de la API de Productos y Carrito de Compras

tags:
  - name: Usuarios
    description: Endpoints relacionados con Usuarios

paths:
  /api/users:
    get:
      summary: Obtener todos los usuarios
      tags: [Usuarios]
      responses:
        '200':
          description: Lista de usuarios obtenida correctamente
        '500':
          description: Error interno del servidor

    post:
      summary: Crear un nuevo usuario
      tags: [Usuarios]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - firstName
                - lastName
                - email
                - password
      responses:
        '201':
          description: Usuario creado correctamente
        '400':
          description: Error en la solicitud
        '500':
          description: Error interno del servidor

  /api/users/{userId}:
 
    delete:
      summary: Eliminar un usuario existente
      tags: [Usuarios]
      parameters:
        - in: path
          name: userId
          required: true
          description: ID del usuario a eliminar
          schema:
            type: string
      responses:
        '200':
          description: Usuario eliminado correctamente
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

    put:
      summary: Actualizar la información de un usuario existente
      tags: [Usuarios]
      parameters:
        - in: path
          name: userId
          required: true
          description: ID del usuario a actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
              required:
                - firstName
                - lastName
      responses:
        '200':
          description: Usuario actualizado correctamente
        '400':
          description: Error en la solicitud
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor