openapi: 3.0.0
info:
  title: API de Productos y Carrito de Compras
  version: 1.0.0
  description: Documentación de la API de Productos y Carrito de Compras
tags:
  - name: Mock
    description: Generar Mock Productos
paths:
 
 /api/mockingproducts:
    get:
      summary: Generar un mock de los productos
      tags: [Mock]
      responses:
        '200':
          description: Mock Generado correctamente
        '500':
          description: Error interno del servidor