openapi: 3.0.0
info:
  title: API de Productos y Carrito de Compras
  version: 1.0.0
  description: Documentación de la API de Productos y Carrito de Compras
tags:
  - name: Carrito
    description: Endpoints relacionados con el carrito
paths:
 
 /api/carts:
    get:
      summary: Obtener los productos en el carrito de compras
      tags: [Carrito]
      responses:
        '200':
          description: Productos en el carrito obtenidos correctamente
        '500':
          description: Error interno del servidor

    post:
      summary: Agregar un producto al carrito de compras
      tags: [Carrito]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: number
              required:
                - productId
                - quantity
      responses:
        '201':
          description: Producto agregado al carrito correctamente
        '400':
          description: Error en la solicitud
        '500':
          description: Error interno del servidor

    delete:
      summary: Eliminar un producto del carrito de compras
      tags: [Carrito]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
              required:
                - productId
      responses:
        '200':
          description: Producto eliminado del carrito correctamente
        '400':
          description: Error en la solicitud
        '500':
          description: Error interno del servidor
